C:\ProgramData\Chocolatey\choco.exe install -y --force GoogleChrome
C:\ProgramData\Chocolatey\choco.exe install -y --force firefox
C:\ProgramData\Chocolatey\choco.exe install -y --force notepadplusplus.install
C:\ProgramData\Chocolatey\choco.exe install -y --force SublimeText3
C:\ProgramData\Chocolatey\choco.exe install -y --force git
C:\ProgramData\Chocolatey\choco.exe install -y --force conemu
C:\ProgramData\Chocolatey\choco.exe install -y --force ccleaner
C:\ProgramData\Chocolatey\choco.exe install -y --force irfanview
C:\ProgramData\Chocolatey\choco.exe install -y --force FoxitReader
C:\ProgramData\Chocolatey\choco.exe install -y --force ollydbg
C:\ProgramData\Chocolatey\choco.exe install -y --force 010editor.install
C:\ProgramData\Chocolatey\choco.exe install -y --force windbg
C:\ProgramData\Chocolatey\choco.exe install -y --force x64dbg.portable
