C:\ProgramData\Chocolatey\choco.exe install -y --force GoogleChrome
C:\ProgramData\Chocolatey\choco.exe install -y --force SysInternals
C:\ProgramData\Chocolatey\choco.exe install -y --force firefox
C:\ProgramData\Chocolatey\choco.exe install -y --force notepadplusplus.install
C:\ProgramData\Chocolatey\choco.exe install -y --force conemu
C:\ProgramData\Chocolatey\choco.exe install -y --force irfanview
C:\ProgramData\Chocolatey\choco.exe install -y --force sumatrapdf
C:\ProgramData\Chocolatey\choco.exe install -y --force windbg
C:\ProgramData\Chocolatey\choco.exe install -y --force x64dbg.portable
C:\ProgramData\Chocolatey\choco.exe install -y --force HxD
